name: gitleaks

on: [pull_request, push, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: gitleaks
      uses: actions/checkout@v3

    - name: Gitleaks Action
      uses: zricethezav/gitleaks-action@master